### ISSUE TITLE
Multiplayer Lobby and Page to Home Leaving Issue

### ISSUE THREAD

**Issue by kenparungao** [belsua/ByteQuiz#23]
tested with v **1.2.0 alpha** by @theiiii 

❌ From Multiplayer lobby to home, may issue sa leaving. nag stuck sa leaving page and di na nakabalik sa home. 

https://github.com/user-attachments/assets/e7a150aa-6660-4219-8f94-fe2323e867fe

**Comment by kenparungao** [comment]
tested with v **1.2.0 alpha** by @theiiii 

Same issue if galing ka lang sa multiplayer page (not lobby) then back to home. @thisellie

**Comment by thisellie** [comment]
Pa-test nalang rito be83c6716e1872fad09ea56b5a0eea8e51232dd3, thanks

**Comment by kenparungao** [comment]
issue fixed by @thisellie
