### ISSUE TITLE
Runner NPC doubling

### ISSUE THREAD

**Issue by kenparungao** [belsua/ByteQuiz#24]
tested on v 1.2.0 alpha 
tested with android phone by @theiiii 
@thisellie 

❌ nagdodoble yung npc na nakaharang sa room sa runner === nawawala yung npc na nakaharang sa next room na expected na nakaharang kapag nangyayari itong issue

===Reference===
https://github.com/user-attachments/assets/947907ea-7d7e-4392-9b8d-6aed078068fb

**Comment by kenparungao** [comment]
tested on branch feature/improve-runner
tested with Unity
tested with android phone build with branch feature/improve-runner
@thisellie

ISSUE STILL PRESENT.

Sample scenario:
Nangyayari everytime na si Player 1 ay sumasagot pa sa Level 1, tapos si Player 2 ay nasa Level 2 na. Kapag nasagutan na ni Player 2 yung tanong sa Level 2, while si Player 1 ay nasa Level 1 pa lang, nadodoble yung npc sa Level 1, pero pag punta ni Player 1 sa Level 2 wala na yung npc.  

===ANOTHER REFERENCE===
https://github.com/user-attachments/assets/1722d948-6340-4cba-a993-f25ab6e8c0b2

**Comment by thisellie** [comment]
@kenparungao oks naman sakin, binuild ko then ininstall ko sa dalawang smartphone working naman. Baka hindi mo napull yung update nung araw na yun?

**Comment by kenparungao** [comment]
solved by @thisellie

**Comment by thisellie** [comment]
ay wait @kenparungao nagloloko nga pag habang nagsasagot 😂

**Comment by kenparungao** [comment]
fixed by @thisellie
