### ISSUE TITLE
tested on branch **feature/improve-runner**

### ISSUE THREAD

**Issue by thisellie** [belsua/ByteQuiz#26]
tested on branch **feature/improve-runner**
tested with Unity with @theiiii 

@thisellie 
**Issue**: Baliktad yung sorting nung standing, si 1st yung lowest tapos 3rd yung highest score

https://github.com/user-attachments/assets/fda445af-2682-48ea-849d-5ea43d7c4696

_Originally posted by @kenparungao in https://github.com/belsua/ByteQuiz/issues/17#issuecomment-2438077736_

**Comment by kenparungao** [comment]
tested on branch **feature/improve-runner** 

issue fixed by @thisellie
