### ISSUE TITLE
runner npc on unity

### ISSUE THREAD

**Issue by kenparungao** [belsua/ByteQuiz#38]
tested with unity current main branch. Di interactable yung npc for runner.

Note: Interactable naman sya kapag build sa phone on latest android bytequiz v 1.2.0, pero lagay ko na rin dito.

https://github.com/user-attachments/assets/7e712b19-3561-4f6d-8a6d-b8385423887f

**Comment by thisellie** [comment]
Na-pull mo na ba yung latest commit sa main? Usually yun yung common problem niya.

**Comment by kenparungao** [comment]
pulled naman. baka sa end ko lang nga may problem, kasi goods naman sa unity mo and sa build.
