### ISSUE TITLE
TerriCon not stealing tiles scores

### ISSUE THREAD

**Issue by kenparungao** [belsua/ByteQuiz#41]
Tested on current main branch
tested on unity v1.2.0

Hindi nanakaw yung scores sa tiles. So If may 3 tiles na na-own si player one tapos na tapalan ni player two yung isang tiles sa 3 na yun, 3 pa rin final scores ni player one.

basically hindi nababawas yung score kapag nanakaw yung tiles.

**Comment by thisellie** [comment]
Di ko ma-reproduce yung issue, naka unity editor + android build ba gamit mo nun?

**Comment by kenparungao** [comment]
> Di ko ma-reproduce yung issue, naka unity editor + android build ba gamit mo nun?

downloaded sa bytequiz website natin yung version na tinest ko. Dapat diba pwede mag agawan ng scores, pero di nababawas. Tama ba sagot ko?

Test ko ulit. Wait.

**Comment by thisellie** [comment]
Maaagaw yung score tsaka tile ni p1 pag nasagutan ng tama ni p2 yung question sa tile ni p1 pero pag mali walang mangyayari

**Comment by thisellie** [comment]
Baguhin ko nalang, mukhang correct answer sa quiz yung pinapakita imbes yung minigame score
