### ISSUE TITLE
Multiplayer chosen subject issue; for sequential purposes.

### ISSUE THREAD

**Issue by kenparungao** [belsua/ByteQuiz#7]
For the subject to be available for play sa multiplayer, dapat lahat ng players na nakajoin is unlocked na yung subject na ipplay nila. For example, if a player has locked subject(s), it will be disabled to be chosen by the host irregardless if unlocked na ng host or others member yung subject na yun.

**Comment by thisellie** [comment]
@kenparungao pa-test if goods na, thanks
